name: Deploy Lambdas

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push Lambda 1
        run: |
          cd lambda1_emotion
          docker build --platform linux/amd64 --provenance=false --output type=registry -t ${{ secrets.ECR_REGISTRY }}/lambda1-emotion:latest .
          aws lambda update-function-code \
            --function-name lambda1-emotion \
            --image-uri ${{ secrets.ECR_REGISTRY }}/lambda1-emotion:latest

      - name: Build & push Lambda 2
        run: |
          cd lambda2_response
          docker build --platform linux/amd64 --provenance=false --output type=registry -t ${{ secrets.ECR_REGISTRY }}/lambda2-response:latest .
          aws lambda update-function-code \
            --function-name lambda2-response \
            --image-uri ${{ secrets.ECR_REGISTRY }}/lambda2-response:latest